# This rule is not used by the project vcluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cloud.ecosysbin.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vcluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: vcluster-editor-role
rules:
- apiGroups:
  - cloud.ecosysbin.com
  resources:
  - vclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.ecosysbin.com
  resources:
  - vclusters/status
  verbs:
  - get
