# This rule is not used by the project vcluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cloud.ecosysbin.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vcluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: vcluster-viewer-role
rules:
- apiGroups:
  - cloud.ecosysbin.com
  resources:
  - vclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.ecosysbin.com
  resources:
  - vclusters/status
  verbs:
  - get
