/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "ecosysbin.com/vcluster-operator/api/v1alpha1"
	applyconfigurationapiv1alpha1 "ecosysbin.com/vcluster-operator/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "ecosysbin.com/vcluster-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VclustersGetter has a method to return a VclusterInterface.
// A group's client should implement this interface.
type VclustersGetter interface {
	Vclusters(namespace string) VclusterInterface
}

// VclusterInterface has methods to work with Vcluster resources.
type VclusterInterface interface {
	Create(ctx context.Context, vcluster *apiv1alpha1.Vcluster, opts v1.CreateOptions) (*apiv1alpha1.Vcluster, error)
	Update(ctx context.Context, vcluster *apiv1alpha1.Vcluster, opts v1.UpdateOptions) (*apiv1alpha1.Vcluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vcluster *apiv1alpha1.Vcluster, opts v1.UpdateOptions) (*apiv1alpha1.Vcluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Vcluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.VclusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Vcluster, err error)
	Apply(ctx context.Context, vcluster *applyconfigurationapiv1alpha1.VclusterApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Vcluster, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, vcluster *applyconfigurationapiv1alpha1.VclusterApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Vcluster, err error)
	VclusterExpansion
}

// vclusters implements VclusterInterface
type vclusters struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.Vcluster, *apiv1alpha1.VclusterList, *applyconfigurationapiv1alpha1.VclusterApplyConfiguration]
}

// newVclusters returns a Vclusters
func newVclusters(c *CloudV1alpha1Client, namespace string) *vclusters {
	return &vclusters{
		gentype.NewClientWithListAndApply[*apiv1alpha1.Vcluster, *apiv1alpha1.VclusterList, *applyconfigurationapiv1alpha1.VclusterApplyConfiguration](
			"vclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Vcluster { return &apiv1alpha1.Vcluster{} },
			func() *apiv1alpha1.VclusterList { return &apiv1alpha1.VclusterList{} },
		),
	}
}
