/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	vclusteroperatorapiv1alpha1 "ecosysbin.com/vcluster-operator/api/v1alpha1"
	versioned "ecosysbin.com/vcluster-operator/pkg/client/clientset/versioned"
	internalinterfaces "ecosysbin.com/vcluster-operator/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "ecosysbin.com/vcluster-operator/pkg/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VclusterInformer provides access to a shared informer and lister for
// Vclusters.
type VclusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.VclusterLister
}

type vclusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVclusterInformer constructs a new informer for Vcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVclusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVclusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVclusterInformer constructs a new informer for Vcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVclusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().Vclusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().Vclusters(namespace).Watch(context.TODO(), options)
			},
		},
		&vclusteroperatorapiv1alpha1.Vcluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *vclusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVclusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vclusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vclusteroperatorapiv1alpha1.Vcluster{}, f.defaultInformer)
}

func (f *vclusterInformer) Lister() apiv1alpha1.VclusterLister {
	return apiv1alpha1.NewVclusterLister(f.Informer().GetIndexer())
}
