/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "ecosysbin.com/vcluster-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VclusterLister helps list Vclusters.
// All objects returned here must be treated as read-only.
type VclusterLister interface {
	// List lists all Vclusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Vcluster, err error)
	// Vclusters returns an object that can list and get Vclusters.
	Vclusters(namespace string) VclusterNamespaceLister
	VclusterListerExpansion
}

// vclusterLister implements the VclusterLister interface.
type vclusterLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Vcluster]
}

// NewVclusterLister returns a new VclusterLister.
func NewVclusterLister(indexer cache.Indexer) VclusterLister {
	return &vclusterLister{listers.New[*apiv1alpha1.Vcluster](indexer, apiv1alpha1.Resource("vcluster"))}
}

// Vclusters returns an object that can list and get Vclusters.
func (s *vclusterLister) Vclusters(namespace string) VclusterNamespaceLister {
	return vclusterNamespaceLister{listers.NewNamespaced[*apiv1alpha1.Vcluster](s.ResourceIndexer, namespace)}
}

// VclusterNamespaceLister helps list and get Vclusters.
// All objects returned here must be treated as read-only.
type VclusterNamespaceLister interface {
	// List lists all Vclusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.Vcluster, err error)
	// Get retrieves the Vcluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.Vcluster, error)
	VclusterNamespaceListerExpansion
}

// vclusterNamespaceLister implements the VclusterNamespaceLister
// interface.
type vclusterNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.Vcluster]
}
